---
- name: Update ansible repo
  hosts: control
  become: no
  tasks:
    - name: Pull latest changes from GitHub
      git:
        repo: https://github.com/aljica/course-virtualiseringsteknik.git
        dest: /home/vagrant/ansible
        update: yes

- name: Configure webserver
  hosts: webserver
  become: yes
  vars_files:
    - /vagrant/secrets.yml
    - vars/main.yml
  roles:
    - webserver